### ISSUE TITLE
Preview Fokus schweizweit statt nur Züri

### ISSUE THREAD

**Issue by hheller** [diluno/bikeable-frontend#20]
https://beta.bikeable.ch/map?embed=true

Einbindung auf den Proveloseiten somit möglich. Zukünftig vlt im Link spezifizierung der Kartenansicht möglich? Somit könnten verschiedene Interessensverbände die Karte mit entsprechendem Zoom einblenden (Bspw. Stadt Basel / Pro Velo Genf etc...)

**Comment by diluno** [comment]
Map-Center und Zoom-Level kann jetzt auch in der URL definiert werden.

zBsp:
https://bikeable.ch/map?embed=true&center=47.4243193,9.3733393&zoom=15
