### ISSUE TITLE
Regionsauswahl

### ISSUE THREAD

**Issue by mgschwend** [diluno/bikeable-frontend#28]

**Comment by hheller** [comment]
What are your open questions, happy to help. Also, is this concerning the Regionenauswahl for the regular users? For the ProVelo ppl, we really need just a way to import or an interface to input the plz

**Comment by mgschwend** [comment]
Wir haben ja das "$store"-Teil, da läuft ja das meiste drüber. Wie machen wir das genau wegen eingeloggten Benutzern/nicht-eingeloggten nutzern? Der Store sollte eigentlich bei eingeloggten Usern die Region vom backend holen und bei nicht-eingeloggten Benutzern was gespeichert ist auslesen, oder?

**Comment by diluno** [comment]
hab doch im slack schon geantwortet :)

> was meinst du mit gespeichert? ich hätt jetzt vorgeschlagen bei nicht-eingeloggten usern machen wir ip location. oder vielleicht brauchen wir noch eine art “allgemeinregion” wo alle spots drin sind, und dann einen knopf “locate me” oder so
