### ISSUE TITLE
Create Spot: Neues Properties für Adresse

### ISSUE THREAD

**Issue by mgschwend** [diluno/bikeable-frontend#30]
- plz
- street
- country
- countryCode

**Comment by LucNaterop** [comment]
zusätzlich 
 - city

**Comment by LucNaterop** [comment]
Ich würde sagen `entry.address` bleibt unverändert aber es gibt zusätzlich `entry.addressDetails`:

```
entry.addressDetails = {
        'countryCode': 'ch',
        'country': country,
        'street': street,
        'plz': plz,
        'city': city
 }
```

**Comment by LucNaterop** [comment]
will heissen, ihr sendet `entry.addressDetails` und bekommt `entry.address` wie vorher zurück
