### ISSUE TITLE
Von Spoteintrag zu Kartenpopup

### ISSUE THREAD

**Issue by hheller** [diluno/bikeable-frontend#40]
Es ist leider irgendwie garnicht intuitiv, wie man zum Kartenpopup kommt. Die Adresse interessiert einem irgendwie nicht, man sucht ein Kartensymbolbild oder ähnliches - habe eine ganze Weile gebraucht bis ich's gecheckt hab!

**Comment by diluno** [comment]
Habe vor dort noch ein Icon hinzuzufügen
