### ISSUE TITLE
Add Spot Symbol auf iFrame

### ISSUE THREAD

**Issue by hheller** [diluno/bikeable-frontend#58]
Bei iFrame wäre die **Option** den Add-Spot button einzublenden sehr wichtig, gerade für die Einbindung auf den ProVelo Seiten. Bei einigen Integrationen möchte der Seitenbesitzer diesen jedoch vlt nicht, z.B. bei Städten und Gemeinden, deshalb Optional.

**Comment by diluno** [comment]
Geht jetzt mit der zusätzlichen Option "controls" in der Embed Url:
https://bikeable.ch/map?embed=true&controls=true
