### ISSUE TITLE
Link von Sponsored Entry wird mit bikeable URL versehen

### ISSUE THREAD

**Issue by hheller** [diluno/bikeable-frontend#60]
Habe den Link von Pro Velo Lausanne auf deren Webseite korrekt im Backend eingefügt aber auf der Webseite wird er dann folgendermassen verlinkt: https://bikeable.ch/www.pro-velo-lausanne.ch 
Habe verschiedenes ausprobiert aber bringe es nicht weg.

**Comment by diluno** [comment]
Geht doch? https://bikeable.ch/partner
Die Links müssen mit http:// oder https:// am Anfang eingefügt werden.

**Comment by hheller** [comment]
siehe printscreens auf slack

**Comment by diluno** [comment]
Auch hier: Links mit http:// am Anfang

**Comment by hheller** [comment]
Ah super, sry, ich dachte das hatte ich schon probiert gehabt...
